### ISSUE TITLE
刚买EFcloud香港就全炸🤣🤣🤣

### ISSUE THREAD

**Issue by pekezz** [KaWaIDeSuNe/xingjiabijichang#1]
<img width="422" alt="Snipaste_2024-11-15_17-20-50" src="https://github.com/user-attachments/assets/65ccbe60-ce67-4f4b-bdb8-79dda379dc09">

**Comment by KaWaIDeSuNe** [comment]
![image](https://github.com/user-attachments/assets/bb67b2b3-5581-44d6-bb66-744a1c20ba47)
我这一直是没问题的，看下代理客户端设置是否正确
